apiVersion: kubeflow.org/v1
kind: "TFJob"
metadata:
  name: id0-cifar10-densenet100-k12-sync-batch512
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    WORKER:
      replicas: 4
      template:

        metadata:
          annotations:
            "tensorspot/num_controller": "1"
            "tensorspot/num_worker": "4"
            "tensorspot/net_request": "119"
            "tensorspot/gpu_limit": "1.0"
            "tensorspot/gpu_request": "1.0"
            "tensorspot/gpu_mem": "17179869184"
            "tensorspot/placement_policy": "tiresias"
            "tensorspot/skewness_level": "1.9"

        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            args:
              - |
                cd /tf_cnn_benchmarks/NVML;
                make;
                JOB=`python /tf_cnn_benchmarks/job_name.py`;
                CONTROLLER_HOST=`python -c "import os, json; tf_config = json.loads(os.environ.get('TF_CONFIG') or '{}'); cluster_config = tf_config.get('cluster', {}); controller_host = cluster_config.get('controller'); print(','.join(controller_host))"`;
                mkdir -p /result/id0_cifar10_densenet100_k12_sync_batch512;
                top -d 0.1 -b | grep tf_cnn > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_cpu.txt &
                echo "id0_cifar10_densenet100_k12_sync_batch512" > /tf_cnn_benchmarks/model.txt;
                STARTTIME=`date "+%H:%M:%S.%N"`;
                echo "$STARTTIME" > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_start_time.txt;

                python /tf_cnn_benchmarks/tf_cnn_benchmarks.py --variable_update=distributed_all_reduce --model=densenet100_k12 --data_name=cifar10 --display_every=1 --batch_size=128 --cross_replica_sync=true --num_batches=248 --num_warmup_batches=0  --controller_host=${CONTROLLER_HOST} --all_reduce_spec=nccl/xring > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_log.txt;

                ENDTIME=`date "+%H:%M:%S.%N"`;
                echo "$ENDTIME" > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_end_time.txt
            ports:
            - containerPort: 2222
              name: tfjob-port
            image: potato4332/tf2-gpu-docker:0.4.5x
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
                nvidia.com/gpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
            twonode: worker

          schedulerName: tensorspot-scheduler


    CONTROLLER:
      replicas: 1
      template:

        metadata:
          annotations:
            "tensorspot/num_controller": "1"
            "tensorspot/num_worker": "4"
            "tensorspot/net_request": "119"
            "tensorspot/placement_policy": "tiresias"
            "tensorspot/skewness_level": "1.9"

        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            args:
              - |
                JOB=`python /tf_cnn_benchmarks/job_name.py`;
                CONTROLLER_HOST=`python -c "import os, json; tf_config = json.loads(os.environ.get('TF_CONFIG') or '{}'); cluster_config = tf_config.get('cluster', {}); controller_host = cluster_config.get('controller'); print(','.join(controller_host))"`;
                mkdir -p /result/id0_cifar10_densenet100_k12_sync_batch512;
                echo "id0_cifar10_densenet100_k12_sync_batch512" > /tf_cnn_benchmarks/model.txt;
                top -d 0.1 -b | grep tf_cnn > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_cpu.txt &
                python /tf_cnn_benchmarks/tf_cnn_benchmarks.py --variable_update=distributed_all_reduce --model=densenet100_k12 --data_name=cifar10 --display_every=1 --batch_size=128 --cross_replica_sync=true --num_batches=248 --num_warmup_batches=0  --controller_host=${CONTROLLER_HOST} --all_reduce_spec=nccl/xring > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_log.txt;
                ENDTIME=`date "+%H:%M:%S.%N"`;
                echo "$ENDTIME" > /result/id0_cifar10_densenet100_k12_sync_batch512/id0_cifar10_densenet100_k12_sync_batch512_${JOB}_end_time.txt
            ports:
            - containerPort: 2222
              name: tfjob-port
            image: potato4332/tf2-cpu-docker:0.5.5x
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
              limits:
                cpu: 5
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
            twonode: worker

          schedulerName: tensorspot-scheduler

 