apiVersion: kubeflow.org/v1
kind: "TFJob"
metadata:
  name: id53-cifar10-resnet44-sync-batch8192
spec:
  runPolicy:
    cleanPodPolicy: None
  tfReplicaSpecs:
    WORKER:
      replicas: 8
      template:
        metadata:
          annotations:
            "tensorspot/num_ps": "8"
            "tensorspot/num_worker": "8"
            "tensorspot/net_request": "0"
            "tensorspot/gpu_limit": "1.0"
            "tensorspot/gpu_request": "1.0"
            "tensorspot/gpu_mem": "16160000000"
            "tensorspot/placement_policy": "spot"
        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            args:
              - cd /tf_cnn_benchmarks/NVML;
                make;
                JOB=`python /tf_cnn_benchmarks/job_name.py`;
                CONTROLLER_HOST=`python -c "import os, json; tf_config = json.loads(os.environ.get('TF_CONFIG') or '{}'); cluster_config = tf_config.get('cluster', {}); controller_host = cluster_config.get('controller'); print(','.join(controller_host))"`;
                mkdir -p /result/id53_cifar10_resnet44_sync_batch8192;
                top -d 0.1 -b | grep tf_cnn > /result/id53_cifar10_resnet44_sync_batch8192/id53_cifar10_resnet44_sync_batch8192_${JOB}_cpu.txt &
                echo "id53_cifar10_resnet44_sync_batch8192" > /tf_cnn_benchmarks/model.txt;
                STARTTIME=`date "+%H:%M:%S.%N"`;
                echo "$STARTTIME" > /result/id53_cifar10_resnet44_sync_batch8192/id53_cifar10_resnet44_sync_batch8192_${JOB}_start_time.txt;
                python /tf_cnn_benchmarks/tf_cnn_benchmarks.py --variable_update=parameter_server --model=resnet44 --data_name=cifar10 --display_every=1 --batch_size=1024 --cross_replica_sync=true --num_batches=648 --num_warmup_batches=0;
                ENDTIME=`date "+%H:%M:%S.%N"`;
                echo "$ENDTIME" > /result/id53_cifar10_resnet44_sync_batch8192/id53_cifar10_resnet44_sync_batch8192_${JOB}_end_time.txt
            ports:
            - containerPort: 2222
              name: tfjob-port
            image: potato4332/tf2-gpu-docker:0.4.5x
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
              limits:
                cpu: 5
                nvidia.com/gpu: 1
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
            twonode: worker
          schedulerName: tensorspot-scheduler
    PS:
      replicas: 8
      template:
        metadata:
          annotations:
            "tensorspot/num_ps": "8"
            "tensorspot/num_worker": "8"
            "tensorspot/net_request": "0"
            "tensorspot/placement_policy": "spot"
        spec:
          containers:
          - name: tensorflow
            command: ["/bin/sh", "-c"]
            args:
              - JOB=`python /tf_cnn_benchmarks/job_name.py`;
                CONTROLLER_HOST=`python -c "import os, json; tf_config = json.loads(os.environ.get('TF_CONFIG') or '{}'); cluster_config = tf_config.get('cluster', {}); controller_host = cluster_config.get('controller'); print(','.join(controller_host))"`;
                mkdir -p /result/id53_cifar10_resnet44_sync_batch8192;
                echo "id53_cifar10_resnet44_sync_batch8192" > /tf_cnn_benchmarks/model.txt;
                top -d 0.1 -b | grep tf_cnn > /result/id53_cifar10_resnet44_sync_batch8192/id53_cifar10_resnet44_sync_batch8192_${JOB}_cpu.txt &
                python /tf_cnn_benchmarks/tf_cnn_benchmarks.py --variable_update=parameter_server --model=resnet44 --data_name=cifar10 --display_every=1 --batch_size=1024 --cross_replica_sync=true --num_batches=648 --num_warmup_batches=0 > /result/id53_cifar10_resnet44_sync_batch8192/id53_cifar10_resnet44_sync_batch8192_${JOB}_log.txt;
                ENDTIME=`date "+%H:%M:%S.%N"`;
                echo "$ENDTIME" > /result/id53_cifar10_resnet44_sync_batch8192/id53_cifar10_resnet44_sync_batch8192_${JOB}_end_time.txt
            ports:
            - containerPort: 2222
              name: tfjob-port
            image: potato4332/tf2-cpu-docker:0.5.5x
            imagePullPolicy: IfNotPresent
            resources:
              requests:
                cpu: 1
              limits:
                cpu: 5
            volumeMounts:
            - mountPath: /result
              name: tfjob-data
            - mountPath: /dev/shm
              name: shmdir
          volumes:
          - name: tfjob-data
            persistentVolumeClaim:
              claimName: tfjob-data-volume-claim
          - name: shmdir
            emptyDir:
              medium: Memory
              sizeLimit: "8G"
          nodeSelector:
            twonode: worker
          schedulerName: tensorspot-scheduler